import { useState } from "react";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { useLocation, useSearchParams } from "wouter";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { motion } from "framer-motion";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { Eye, EyeOff, Loader2, CheckCircle2, XCircle, KeyRound } from "lucide-react";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { apiRequest } from "@/lib/queryClient";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { useToast } from "@/hooks/use-toast";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { calculatePasswordStrength } from "@/lib/password-strength";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import { cn } from "@/lib/utils";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import Barcode from "@/components/ui/barcode";
import ThorxSpinner from "@/components/ui/thorx-spinner";
import AuthNav from "@/components/auth/AuthNav";
import ThorxSpinner from "@/components/ui/thorx-spinner";

type ResetStatus = "form" | "success" | "invalid";

/**
 * Landing page for the emailed password-reset link
 * (/reset-password?token=...) generated by POST /api/forgot-password.
 * This is a plain public route (see App.tsx) rather than wrapped in
 * PublicOnlyRoute/ProtectedRoute — the token in the URL, not session state,
 * is what authorizes the password change (server/routes.ts POST
 * /api/reset-password), so it must work the same whether or not the visitor
 * currently has an active session.
 */
export default function ResetPasswordPage() {
  const [, setLocation] = useLocation();
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");
  const { toast } = useToast();

  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [status, setStatus] = useState<ResetStatus>(token ? "form" : "invalid");
  const [errorMessage, setErrorMessage] = useState("");

  const strength = calculatePasswordStrength(password);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting || !token) return;

    if (password.length < 8) {
      toast({ title: "Weak Password", description: "Password must be at least 8 characters.", variant: "destructive" });
      return;
    }
    if (password !== confirmPassword) {
      toast({ title: "Passwords Don't Match", description: "Please re-enter matching passwords.", variant: "destructive" });
      return;
    }

    setIsSubmitting(true);
    try {
      await apiRequest("POST", "/api/reset-password", { token, password });
      setStatus("success");
    } catch (err: any) {
      const message = (err?.message as string | undefined)?.replace(/^\d+:\s*/, "") || "Failed to reset password. Please try again.";
      // Token-level failures (invalid / already used / expired) all come back
      // from the server as messages that mention "reset link" — route those
      // to the dead-end state instead of leaving the user stuck on a form
      // that can never succeed. Anything else (e.g. a validation edge case)
      // stays on the form so they can just retry.
      if (message.toLowerCase().includes("link")) {
        setErrorMessage(message);
        setStatus("invalid");
      } else {
        toast({ title: "Error", description: message, variant: "destructive" });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <motion.div
      className="auth-page overflow-x-hidden"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >

      <AuthNav />

      <section className="cinematic-section active min-h-screen pb-8 overflow-y-auto overscroll-behavior-contain">
        <div className="max-w-7xl mx-auto px-4 md:px-8 pb-20">
          <div className="text-center mb-4 md:mb-6">
            <Barcode variant="bold" className="w-32 md:w-48 h-8 md:h-10 mx-auto" />
          </div>

          <motion.div
            className="w-full max-w-3xl mx-auto mb-8 px-2 md:px-0"
            initial={{ y: -40, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ type: "spring", damping: 14, stiffness: 120, mass: 1, delay: 0.1 }}
          >
            <div className="split-card bg-white border-2 md:border-[3px] border-black/15 rounded-2xl p-3 md:p-6 lg:p-10 overflow-visible w-full">
              <div className="max-w-[480px] mx-auto w-full space-y-6 md:space-y-8">

                {status === "invalid" && (
                  <div className="text-center space-y-4 py-8">
                    <div className="w-16 h-16 mx-auto bg-black rounded-2xl flex items-center justify-center border-2 border-black">
                      <XCircle className="w-7 h-7 text-white" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-black tracking-tight">LINK NO LONGER VALID</h2>
                    <p className="text-sm text-muted-foreground max-w-sm mx-auto">
                      {errorMessage || "This password reset link is invalid, expired, or missing a token."}
                    </p>
                    <button
                      type="button"
                      onClick={() => setLocation("/auth")}
                      className="text-sm font-bold text-primary hover:text-black transition-colors"
                      data-testid="button-reset-back-to-login"
                    >
                      ← BACK TO SIGN IN
                    </button>
                  </div>
                )}

                {status === "success" && (
                  <div className="text-center space-y-4 py-8">
                    <div className="w-16 h-16 mx-auto bg-black rounded-2xl flex items-center justify-center border-2 border-black">
                      <CheckCircle2 className="w-7 h-7 text-white" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-black tracking-tight">PASSWORD UPDATED</h2>
                    <p className="text-sm text-muted-foreground max-w-sm mx-auto">
                      Your password has been changed and every other session has been signed out. Please sign in again with your new password.
                    </p>
                    <button
                      type="button"
                      onClick={() => setLocation("/auth")}
                      className="w-full bg-black text-white font-black text-sm uppercase tracking-widest py-4 border-2 border-black rounded-lg hover:bg-primary hover:border-primary transition-colors"
                      data-testid="button-reset-continue"
                    >
                      CONTINUE TO SIGN IN
                    </button>
                  </div>
                )}

                {status === "form" && (
                  <>
                    <div className="text-center space-y-3">
                      <div className="w-16 h-16 mx-auto bg-black rounded-2xl flex items-center justify-center border-2 border-black">
                        <KeyRound className="w-7 h-7 text-white" />
                      </div>
                      <h2 className="text-2xl md:text-3xl font-black tracking-tight">SET NEW PASSWORD</h2>
                      <p className="text-sm text-muted-foreground max-w-sm mx-auto">
                        Choose a strong new password for your account.
                      </p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-4">
                      <div className="space-y-2">
                        <label className="text-[10px] font-black tracking-[0.2em] text-black/50 uppercase">New Password</label>
                        <div className="relative">
                          <input
                            type={showPassword ? "text" : "password"}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full border-2 border-black/15 rounded-lg text-base py-3 px-4 pr-12 outline-none focus:border-primary transition-colors"
                            placeholder="At least 8 characters"
                            autoFocus
                            data-testid="input-reset-new-password"
                          />
                          <button
                            type="button"
                            onClick={() => setShowPassword(!showPassword)}
                            className="absolute right-4 top-1/2 -translate-y-1/2 text-black/40 hover:text-black transition-colors"
                            tabIndex={-1}
                          >
                            {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                          </button>
                        </div>
                        {password && (
                          <div className="space-y-1.5 pt-1">
                            <div className="flex gap-1">
                              {[1, 2, 3, 4].map((i) => (
                                <div
                                  key={i}
                                  className={cn(
                                    "h-1 flex-1 rounded-full transition-colors",
                                    i <= strength.level ? strength.color : "bg-black/10"
                                  )}
                                />
                              ))}
                            </div>
                            <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{strength.label}</p>
                          </div>
                        )}
                      </div>

                      <div className="space-y-2">
                        <label className="text-[10px] font-black tracking-[0.2em] text-black/50 uppercase">Confirm Password</label>
                        <input
                          type={showPassword ? "text" : "password"}
                          value={confirmPassword}
                          onChange={(e) => setConfirmPassword(e.target.value)}
                          className="w-full border-2 border-black/15 rounded-lg text-base py-3 px-4 outline-none focus:border-primary transition-colors"
                          placeholder="Re-enter password"
                          data-testid="input-reset-confirm-password"
                        />
                      </div>

                      <button
                        type="submit"
                        disabled={isSubmitting}
                        className="w-full bg-black text-white font-black text-sm uppercase tracking-widest py-4 border-2 border-black rounded-lg hover:bg-primary hover:border-primary transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                        data-testid="button-reset-submit"
                      >
                        {isSubmitting ? (
                          <>
                            <ThorxSpinner size={16} />
                            UPDATING…
                          </>
                        ) : (
                          "SET NEW PASSWORD"
                        )}
                      </button>
                    </form>
                  </>
                )}

              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </motion.div>
  );
}
